# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetails',
            name='PatientReportedAge',
            field=models.CharField(max_length=100),
        ),
    ]
