# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20160808_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetails',
            name='PatientBirthDate',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studydetails',
            name='StudyDate',
            field=models.DateTimeField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studydetails',
            name='StudyID',
            field=models.CharField(max_length=50),
        ),
    ]
