# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20160808_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetails',
            name='Age_Days',
            field=models.CharField(max_length=50),
        ),
    ]
