# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20160808_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetails',
            name='PatientBirthDate',
            field=models.DateTimeField(verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='PatientID',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studydetails',
            name='StudyDate',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
