# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20160809_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetails',
            name='Age_Days',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='PatientBirthDate',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='studydetails',
            name='StudyDate',
            field=models.CharField(max_length=200),
        ),
    ]
