# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-10 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20160810_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studydetails',
            name='StudyID',
            field=models.CharField(max_length=128),
        ),
    ]
