# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-10 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_remove_studydetails_studyid'),
    ]

    operations = [
        migrations.AddField(
            model_name='studydetails',
            name='StudyID',
            field=models.CharField(default=236, max_length=128),
            preserve_default=False,
        ),
    ]
