# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-11 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_auto_20160810_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetails',
            name='PatientID',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='studydetails',
            name='StudyDescription',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='studydetails',
            name='StudyID',
            field=models.CharField(max_length=128),
        ),
    ]
