# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_auto_20160811_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studydetails',
            name='StudyID',
            field=models.CharField(max_length=100),
        ),
    ]
