# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_auto_20160829_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalheaderinfo',
            name='HeaderID',
            field=models.CharField(default=4564651348, max_length=100),
            preserve_default=False,
        ),
    ]
