# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0023_additionalheaderinfo_headerid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additionalheaderinfo',
            old_name='HeaderID',
            new_name='SeriesID',
        ),
        migrations.RemoveField(
            model_name='additionalheaderinfo',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='additionalheaderinfo',
            name='series',
        ),
        migrations.AddField(
            model_name='additionalheaderinfo',
            name='PatientID',
            field=models.CharField(default=54897854, max_length=25),
            preserve_default=False,
        ),
    ]
