# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0025_auto_20160830_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalheaderinfo',
            name='PatientID',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='additionalheaderinfo',
            name='PrimarySliceDirection',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='additionalheaderinfo',
            name='ProtocolName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='additionalheaderinfo',
            name='VoxelSizes',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='additionalheaderinfo',
            name='dimensions',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='additionalheaderinfo',
            name='fov',
            field=models.CharField(max_length=100),
        ),
    ]
