# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0026_auto_20160831_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetails',
            name='PatientBirthDate',
            field=models.DateTimeField(max_length=25),
        ),
        migrations.AlterField(
            model_name='studydetails',
            name='StudyDate',
            field=models.DateTimeField(max_length=25),
        ),
    ]
