# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-08 18:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0031_auto_20160831_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalheaderinfo',
            name='SeriesID',
        ),
        migrations.RemoveField(
            model_name='additionalheaderinfo',
            name='VoxelSizes',
        ),
        migrations.RemoveField(
            model_name='additionalheaderinfo',
            name='dimensions',
        ),
        migrations.RemoveField(
            model_name='additionalheaderinfo',
            name='fov',
        ),
    ]
