# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-08 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0032_auto_20160908_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalheaderinfo',
            name='VoxelSizes',
            field=models.CharField(default=4154989, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='additionalheaderinfo',
            name='dimensions',
            field=models.CharField(default=84864, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='additionalheaderinfo',
            name='fov',
            field=models.CharField(default=454984, max_length=50),
            preserve_default=False,
        ),
    ]
