# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-08 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0033_auto_20160908_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdetails',
            name='ProtocolName',
            field=models.CharField(default=54854984, max_length=100),
            preserve_default=False,
        ),
    ]
