# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-08 20:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0035_patientdetails_primaryslicedirection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdetails',
            name='PrimarySliceDirection',
        ),
    ]
