# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-15 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0037_remove_patientdetails_protocolname'),
    ]

    operations = [
        migrations.AddField(
            model_name='seriesdetails',
            name='ProtocolName',
            field=models.CharField(default=56448456, max_length=100),
            preserve_default=False,
        ),
    ]
