# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-15 15:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0038_seriesdetails_protocolname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seriesdetails',
            name='ProtocolName',
        ),
    ]
